# Generated by Django 5.0.4 on 2024-05-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_api', '0004_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='Dname',
        ),
    ]
